{{- if not .Values.secret.useExisting }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-backup-tool
  namespace: {{ .Values.namespace.name }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.secret.isVault }}
  # Для ArgoCD Vault Plugin - используем плейсхолдеры как есть
  {{ .Values.secret.secretKeys.grafanaToken }}: {{ .Values.grafana.token | quote }}
  {{ .Values.secret.secretKeys.grafanaAdminPassword }}: {{ .Values.grafana.admin.password | quote }}
  {{ .Values.secret.secretKeys.awsAccessKeyId }}: {{ .Values.backup.s3.accessKey | quote }}
  {{ .Values.secret.secretKeys.awsSecretAccessKey }}: {{ .Values.backup.s3.secretKey | quote }}
  {{- else }}
  # Для обычного Helm - используем base64 кодирование
  {{ .Values.secret.secretKeys.grafanaToken }}: {{ .Values.grafana.token | b64enc | quote }}
  {{ .Values.secret.secretKeys.grafanaAdminPassword }}: {{ .Values.grafana.admin.password | b64enc | quote }}
  {{ .Values.secret.secretKeys.awsAccessKeyId }}: {{ .Values.backup.s3.accessKey | b64enc | quote }}
  {{ .Values.secret.secretKeys.awsSecretAccessKey }}: {{ .Values.backup.s3.secretKey | b64enc | quote }}
  {{- end }}
{{- end }}